using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections;

namespace SearchEnging.utils.nlp
{
    public class RemoveStopWordsClass
    {
        ArrayList StopWords;

        public RemoveStopWordsClass()
        {
            StopWords = new ArrayList();
            // إضافة
            StopWords.Add("الى");
            //StopWords.Add("حول");
            StopWords.Add("في"); StopWords.Add("على");
            StopWords.Add("إلى"); StopWords.Add("من");
            StopWords.Add("عن"); StopWords.Add("هناك");
            StopWords.Add("أو"); StopWords.Add("ثم");
            StopWords.Add("نحن"); StopWords.Add("أنا");
            StopWords.Add("أنتم"); StopWords.Add("أنت");
            StopWords.Add("أنتما"); StopWords.Add("إياه");
            StopWords.Add("أنتن"); StopWords.Add("إياها");
            StopWords.Add("هو"); StopWords.Add("إياهما");
            StopWords.Add("هي"); StopWords.Add("إياهم");
            StopWords.Add("هما"); StopWords.Add("إياهن");
            StopWords.Add("هم"); StopWords.Add("إياك");
            StopWords.Add("هن"); StopWords.Add("إياكما");
            StopWords.Add("تلك"); StopWords.Add("إياكم");
            StopWords.Add("ذا"); StopWords.Add("إياكن");
            StopWords.Add("ذاك"); StopWords.Add("إياي");
            StopWords.Add("ذلك"); StopWords.Add("إيانا");
            StopWords.Add("ذان"); StopWords.Add("أولاء");
            StopWords.Add("ذانك"); StopWords.Add("أولئك");
            StopWords.Add("ذه"); StopWords.Add("أولالك");
            StopWords.Add("ذين"); StopWords.Add("ذي");
            StopWords.Add("ذينك"); StopWords.Add("هؤلاء");
            StopWords.Add("هذان"); StopWords.Add("هاتان");
            StopWords.Add("هذه"); StopWords.Add("هانه");
            StopWords.Add("هذي"); StopWords.Add("هاتي");
            StopWords.Add("هذين"); StopWords.Add("هاتين");
            StopWords.Add("هنا"); StopWords.Add("هذا");
            StopWords.Add("من"); StopWords.Add("هنالك");
            StopWords.Add("ما"); StopWords.Add("التي");
            StopWords.Add("أين"); StopWords.Add("الذي");
            StopWords.Add("أي"); StopWords.Add("اللذين");
            StopWords.Add("أيان"); StopWords.Add("الذين");
            StopWords.Add("حيثما"); StopWords.Add("اللذان");
            StopWords.Add("كيفما"); StopWords.Add("اللاتي");
            StopWords.Add("متى"); StopWords.Add("اللتان");
            StopWords.Add("هماكم"); StopWords.Add("اللتيا");
            StopWords.Add("كيف"); StopWords.Add("اللتيا");
            StopWords.Add("ماذا"); StopWords.Add("اللواتي");
            StopWords.Add("هلم"); StopWords.Add("كأي");
            StopWords.Add("قلما"); StopWords.Add("كأين");
            StopWords.Add("إن"); StopWords.Add("إليك");
            StopWords.Add("لا"); StopWords.Add("إليكم");
            StopWords.Add("لات"); StopWords.Add("إليكما");
            StopWords.Add("أن"); StopWords.Add("إليكن");
            StopWords.Add("كأن"); StopWords.Add("عليك");
            StopWords.Add("لعل"); StopWords.Add("ها");
            StopWords.Add("لكن"); StopWords.Add("هاك");
            StopWords.Add("أي"); StopWords.Add("ليت");
            StopWords.Add("أيا"); StopWords.Add("أجل");
            StopWords.Add("بل"); StopWords.Add("إذما");
            StopWords.Add("بلا"); StopWords.Add("إذن");
            StopWords.Add("حتى"); StopWords.Add("إذ");
            StopWords.Add("سوف"); StopWords.Add("ألا");
            StopWords.Add("عل"); StopWords.Add("إلى");
            StopWords.Add("في"); StopWords.Add("أم");
            StopWords.Add("كلا"); StopWords.Add("أما");
            StopWords.Add("هلا"); StopWords.Add("كي");
            StopWords.Add("وا"); StopWords.Add("لم");
            StopWords.Add("إذ"); StopWords.Add("لن");
            StopWords.Add("إلا"); StopWords.Add("لو");
            StopWords.Add("على"); StopWords.Add("لولا");
            StopWords.Add("عن"); StopWords.Add("لوما");
            StopWords.Add("قد"); StopWords.Add("هل");
            StopWords.Add("عدا"); StopWords.Add("لما");
            StopWords.Add("بعض"); StopWords.Add("مذ");
            StopWords.Add("سوى"); StopWords.Add("منذ");
            StopWords.Add("غير"); StopWords.Add("حاشا");
            StopWords.Add("كل"); StopWords.Add("خلا");
            StopWords.Add("ذات"); StopWords.Add("لعمر");
            StopWords.Add("عندما"); StopWords.Add("مثل");
            StopWords.Add("كلما"); StopWords.Add("مع");
            StopWords.Add("قبل"); StopWords.Add("نحو");
            StopWords.Add("خلف"); StopWords.Add("حيث");
            StopWords.Add("أمام"); StopWords.Add("كلتا");
            StopWords.Add("تحت"); StopWords.Add("سيما");
            StopWords.Add("يمين"); StopWords.Add("أصلاً");
            StopWords.Add("أصبح"); StopWords.Add("بين");
            StopWords.Add("كان"); StopWords.Add("صار");
            StopWords.Add("ليس"); StopWords.Add("ظل");
            StopWords.Add("انفك"); StopWords.Add("عاد");
            StopWords.Add("مادام"); StopWords.Add("برح");
            StopWords.Add("مازال"); StopWords.Add("مافتئ");
            StopWords.Add("فوق"); StopWords.Add("و");

            StopWords.Add("I"); StopWords.Add("i");
            StopWords.Add("A"); StopWords.Add("a");
            StopWords.Add("an");
            StopWords.Add("as");
            StopWords.Add("at");
            StopWords.Add("by");
            StopWords.Add("he");
            StopWords.Add("his");
            StopWords.Add("me");
            StopWords.Add("thou");
            StopWords.Add("us");
            StopWords.Add("who");
            StopWords.Add("against");
            StopWords.Add("amid");
            StopWords.Add("amidst");
            StopWords.Add("among");
            StopWords.Add("amongst");
            StopWords.Add("and");
            StopWords.Add("anybody");
            StopWords.Add("anyone");
            StopWords.Add("because");
            StopWords.Add("beside");
            StopWords.Add("circa");
            StopWords.Add("despite");
            StopWords.Add("during");
            StopWords.Add("everybody");
            StopWords.Add("everyone");
            StopWords.Add("for");
            StopWords.Add("from");
            StopWords.Add("her");
            StopWords.Add("hers");
            StopWords.Add("herself");
            StopWords.Add("him");
            StopWords.Add("himself");
            StopWords.Add("hisself");
            StopWords.Add("idem");
            StopWords.Add("if");
            StopWords.Add("into");
            StopWords.Add("it");
            StopWords.Add("its");
            StopWords.Add("itself");
            StopWords.Add("myself");
            StopWords.Add("nor");
            StopWords.Add("of");
            StopWords.Add("oneself");
            StopWords.Add("onto");
            StopWords.Add("our");
            StopWords.Add("ourself");
            StopWords.Add("ourselves");
            StopWords.Add("per");
            StopWords.Add("she");
            StopWords.Add("since");
            StopWords.Add("than");
            StopWords.Add("that");
            StopWords.Add("the");
            StopWords.Add("thee");
            StopWords.Add("theirs");
            StopWords.Add("them");
            StopWords.Add("themselves");
            StopWords.Add("they");
            StopWords.Add("thine");
            StopWords.Add("this");
            StopWords.Add("thyself");
            StopWords.Add("to");
            StopWords.Add("tother");
            StopWords.Add("toward");
            StopWords.Add("towards");
            StopWords.Add("unless");
            StopWords.Add("until");
            StopWords.Add("upon");
            StopWords.Add("versus");
            StopWords.Add("via");
            StopWords.Add("we");
            StopWords.Add("what");
            StopWords.Add("whatall");
            StopWords.Add("whereas");
            StopWords.Add("which");
            StopWords.Add("whichever");
            StopWords.Add("whichsoever");
            StopWords.Add("whoever");
            StopWords.Add("whom");
            StopWords.Add("whomever");
            StopWords.Add("whomso");
            StopWords.Add("whomsoever");
            StopWords.Add("whose");
            StopWords.Add("whosoever");
            StopWords.Add("with");
            StopWords.Add("without");
            StopWords.Add("ye");
            StopWords.Add("you");
            StopWords.Add("you-all");
            StopWords.Add("yours");
            StopWords.Add("yourself");
            StopWords.Add("yourselves");
            StopWords.Add("aboard");
            StopWords.Add("about");
            StopWords.Add("above");
            StopWords.Add("across");
            StopWords.Add("after");
            StopWords.Add("all");
            StopWords.Add("along");
            StopWords.Add("alongside");
            StopWords.Add("although");
            StopWords.Add("another");
            StopWords.Add("anti");
            StopWords.Add("any");
            StopWords.Add("anything");
            StopWords.Add("around");
            StopWords.Add("astride");
            StopWords.Add("aught");
            StopWords.Add("bar");
            StopWords.Add("barring");
            StopWords.Add("before");
            StopWords.Add("behind");
            StopWords.Add("below");
            StopWords.Add("beneath");
            StopWords.Add("besides");
            StopWords.Add("between");
            StopWords.Add("beyond");
            StopWords.Add("both");
            StopWords.Add("but");
            StopWords.Add("concerning");
            StopWords.Add("considering");
            StopWords.Add("down");
            StopWords.Add("each");
            StopWords.Add("either");
            StopWords.Add("enough");
            StopWords.Add("except");
            StopWords.Add("excepting");
            StopWords.Add("excluding");
            StopWords.Add("few");
            StopWords.Add("fewer");
            StopWords.Add("following");
            StopWords.Add("ilk");
            StopWords.Add("in");
            StopWords.Add("including");
            StopWords.Add("inside");
            StopWords.Add("like");
            StopWords.Add("many");
            StopWords.Add("mine");
            StopWords.Add("minus");
            StopWords.Add("more");
            StopWords.Add("most");
            StopWords.Add("naught");
            StopWords.Add("near");
            StopWords.Add("neither");
            StopWords.Add("nobody");
            StopWords.Add("none");
            StopWords.Add("nothing");
            StopWords.Add("notwithstanding");
            StopWords.Add("off");
            StopWords.Add("on");
            StopWords.Add("opposite");
            StopWords.Add("other");
            StopWords.Add("otherwise");
            StopWords.Add("outside");
            StopWords.Add("over");
            StopWords.Add("own");
            StopWords.Add("past");
            StopWords.Add("pending");
            StopWords.Add("plus");
            StopWords.Add("regarding");
            StopWords.Add("round");
            StopWords.Add("save");
            StopWords.Add("self");
            StopWords.Add("several");
            StopWords.Add("so");
            StopWords.Add("some");
            StopWords.Add("somebody");
            StopWords.Add("someone");
            StopWords.Add("something");
            StopWords.Add("somewhat");
            StopWords.Add("such");
            StopWords.Add("suchlike");
            StopWords.Add("sundry");
            StopWords.Add("there");
            StopWords.Add("though");
            StopWords.Add("through");
            StopWords.Add("throughout");
            StopWords.Add("till");
            StopWords.Add("twain");
            StopWords.Add("under");
            StopWords.Add("underneath");
            StopWords.Add("unlike");
            StopWords.Add("up");
            StopWords.Add("various");
            StopWords.Add("vis-a-vis");
            StopWords.Add("whatever");
            StopWords.Add("whatsoever");
            StopWords.Add("when");
            StopWords.Add("wherewith");
            StopWords.Add("wherewithal");
            StopWords.Add("while");
            StopWords.Add("within");
            StopWords.Add("worth");
            StopWords.Add("yet");
            StopWords.Add("yon");
            StopWords.Add("yonder");
            StopWords.Add("or");
            StopWords.Add("not");
        }

        public bool isStopWord(String str)
        {
            return StopWords.Contains(str);
        }

        public string removing(string W)
        {
            string Stem = "";
            W = W.Trim();

            string S = W.ToString();
            if (!StopWords.Contains(S))
            {
                Stem += S;
            }
            return Stem;
        }
    }

}